name: Github Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCwi04PRBTqOoXohKAz6HJ9A
          comment_tag_name: YOUTUBE-CARDS-EN
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCwi04PRBTqOoXohKAz6HJ9A
          comment_tag_name: YOUTUBE-CARDS-AR
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true